### PR TITLE
Pressing enter from coupon code field triggers place order

### PR DESCRIPTION
**Pull request by rajeev-k-tomy**

### CODE REVIEW

**Comment by rajeev-k-tomy** [comment]
@jesse-deboer Can you review this please

**Review by ilker-capli — APPROVED** [review]
Thank you @rajeev-k-tomy , I can not reproduce the issue in this PR.

**Comment by ilker-capli** [comment]
I've also faced another issue with this PR. @rajeev-k-tomy 

When I apply discount code on checkout and try to complete order, It's blocking place order.
Throws a validationError.

**Comment by rajeev-k-tomy** [comment]
@ilker-capli Thanks for testing it. This is really tricky. The second scenario is the behaviour we actually implemented here. We added a validation for coupon code field in such a way that, if there is an entry there and it is not validated, then the entire checkout is disabled till customer complete it.

I think we should go for some other solution here in order to avoid issues such as above reported. Need some time to think about this. At the moment, i am out of ideas

**Review by wigman — APPROVED** [review]

**Comment by rajeev-k-tomy** [comment]
This is now merged as it fixes the main issue. I know that the minor issues still present. Spending huge amount of time to fix this UI issue probably elongate the next release. We can fix the minor issues mentioned in this thread in a later release.

**Pull request merged**
